import { SkillsSection } from './skills/skills-section';
export function PersonalSections({ view }) {
    if (view === 'studio')
        return <section className="personal-section about-section" aria-labelledby="about-title"><div><p className="eyebrow">A little about me</p><h2 id="about-title">Curious by nature.<br /><em>Creative by practice.</em></h2><p className="personal-lead">I’m Jeff A. Gentapanan, a BSIT student at Western Institute of Technology, learning front-end development and UI/UX design.</p><p className="muted personal-copy">I’m still pretty new to the world of front-end development and design, but I’m enjoying the process of exploring how it all works. I’m always looking for new things to learn and ways to expand what I know.</p><a className="button solid" href="#projects">Explore my projects ↗</a></div><figure className="portrait"><img src="/portfolio/profile.jpg" alt="Jeff A. Gentapanan" width="600" height="700" loading="lazy"/><figcaption><span>Jeff A. Gentapanan</span><span>Designing. Building. Learning.</span></figcaption></figure></section>;
    if (view === 'skills')
        return <SkillsSection />;
    if (view === 'resume')
        return <section className="personal-section" aria-labelledby="resume-title"><p className="eyebrow">Background</p><h2 id="resume-title">A little context.<br /><em>The next chapter.</em></h2><dl className="resume-details">{[['Name', 'Jeff A. Gentapanan'], ['Address', 'Igcocolo, Guimbal, Iloilo'], ['Education', 'BSIT — Western Institute of Technology'], ['Birthday', 'May 25, 2004']].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="resume-actions"><a className="button solid" href="https://drive.google.com/file/d/1zBMBMWVx96HQH1sKYThS32GJTFgdBkIW/view?usp=sharing" target="_blank" rel="noopener noreferrer">View résumé ↗</a><a className="button" href="/portfolio/Jeff-Gentapanan-Resume.pdf" download="Jeff-Gentapanan-Resume.pdf">Download PDF ↓</a></div></section>;
    return <section className="personal-section" aria-labelledby="contact-title"><p className="eyebrow">Start a conversation</p><h2 id="contact-title">Have something<br /><em>in mind?</em></h2><div className="contact-columns"><div><p className="personal-lead">I’m open to new opportunities and collaborations. Let’s talk.</p><a className="contact-email" href="mailto:jeff.gentapanan2004525@gmail.com">jeff.gentapanan2004525@gmail.com ↗</a><a className="contact-phone" href="tel:+639944935058">09944935058</a><p className="muted">Philippines</p><a className="text-button" href="https://www.linkedin.com/in/jeff-gentapanan-4b76b8370/" target="_blank" rel="noopener noreferrer">LinkedIn profile ↗</a></div><form className="jeff-contact-form" action="https://formsubmit.co/jeff.gentapanan2004525@gmail.com" method="POST"><label htmlFor="contact-name">Name<input id="contact-name" name="name" autoComplete="name" required maxLength={100}/></label><label htmlFor="contact-email">Email<input id="contact-email" type="email" name="email" autoComplete="email" required maxLength={254}/></label><label htmlFor="contact-message">Message<textarea id="contact-message" name="message" rows={5} required maxLength={5000}/></label><p className="muted">Your message is sent to Jeff through FormSubmit.</p><button className="button solid" type="submit">Send message ↗</button></form></div></section>;
}
